# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrasi():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrasi(self):
    # Test name: Registrasi
    # Step # | name | target | value
    # 1 | open | http://localhost/penjualan_elektronik/pelanggan/ | 
    self.driver.get("http://localhost/penjualan_elektronik/pelanggan/")
    # 2 | setWindowSize | 889x694 | 
    self.driver.set_window_size(889, 694)
    # 3 | click | css=.sli-settings | 
    self.driver.find_element(By.CSS_SELECTOR, ".sli-settings").click()
    # 4 | click | linkText=Registrasi Pelanggan | 
    self.driver.find_element(By.LINK_TEXT, "Registrasi Pelanggan").click()
    # 5 | click | name=nama_pelanggan | 
    self.driver.find_element(By.NAME, "nama_pelanggan").click()
    # 6 | type | name=nama_pelanggan | panji
    self.driver.find_element(By.NAME, "nama_pelanggan").send_keys("panji")
    # 7 | click | name=alamat_pelanggan | 
    self.driver.find_element(By.NAME, "alamat_pelanggan").click()
    # 8 | type | name=alamat_pelanggan | jl.jakarta
    self.driver.find_element(By.NAME, "alamat_pelanggan").send_keys("jl.jakarta")
    # 9 | click | name=telpon_pelanggan | 
    self.driver.find_element(By.NAME, "telpon_pelanggan").click()
    # 10 | type | name=telpon_pelanggan | 0812345
    self.driver.find_element(By.NAME, "telpon_pelanggan").send_keys("0812345")
    # 11 | click | name=kota_pelanggan | 
    self.driver.find_element(By.NAME, "kota_pelanggan").click()
    # 12 | type | name=kota_pelanggan | semarang
    self.driver.find_element(By.NAME, "kota_pelanggan").send_keys("semarang")
    # 13 | click | name=Username | 
    self.driver.find_element(By.NAME, "Username").click()
    # 14 | type | name=Username | panji
    self.driver.find_element(By.NAME, "Username").send_keys("panji")
    # 15 | click | name=Password | 
    self.driver.find_element(By.NAME, "Password").click()
    # 16 | type | name=Password | panji
    self.driver.find_element(By.NAME, "Password").send_keys("panji")
    # 17 | click | css=.button-box > button | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-box > button").click()
    # 18 | close |  | 
    self.driver.close()
  
