# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomeTesting():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homeTesting(self):
    # Test name: Home_Testing
    # Step # | name | target | value
    # 1 | open | http://localhost/penjualanelektronik/pelanggan | 
    self.driver.get("http://localhost/penjualanelektronik/pelanggan")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | linkText=Product | 
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    # 4 | click | linkText=Add to Cart | 
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    # 5 | click | css=.pt-40 .cart-price | 
    self.driver.find_element(By.CSS_SELECTOR, ".pt-40 .cart-price").click()
    # 6 | click | css=.show .default-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".show .default-btn").click()
    # 7 | click | css=.product-remove .sli | 
    self.driver.find_element(By.CSS_SELECTOR, ".product-remove .sli").click()
    # 8 | verifyText | css=tr:nth-child(1) > td | Tidak ada Data
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td").text == "Tidak ada Data"
    # 9 | click | linkText=Product | 
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    # 10 | click | css=.shop-list-price-action-wrap:nth-child(5) .list-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".shop-list-price-action-wrap:nth-child(5) .list-cart").click()
    # 11 | click | css=.pt-40 .cart-price | 
    self.driver.find_element(By.CSS_SELECTOR, ".pt-40 .cart-price").click()
    # 12 | click | css=.show .default-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".show .default-btn").click()
    # 13 | click | name=submit | 
    self.driver.find_element(By.NAME, "submit").click()
    # 14 | click | linkText=Product | 
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    # 15 | click | linkText=Add to Cart | 
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    # 16 | click | css=.pt-40 .cart-price | 
    self.driver.find_element(By.CSS_SELECTOR, ".pt-40 .cart-price").click()
    # 17 | close |  | 
    self.driver.close()
  
